# Generated by Django 3.2.7 on 2021-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('sku_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('salt_name', models.CharField(max_length=50)),
                ('drug_form', models.CharField(max_length=50)),
                ('Pack_size', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('product_banned_flag', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
